/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DSYF5tYRlOC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AddCourse() {
  return (
    (<Card className="w-full max-w-3xl">
      <CardHeader className="flex flex-row space-y-0 items-start gap-2">
        <div className="grid gap-1">
          <CardTitle>Course Details</CardTitle>
          <CardDescription>Update the course details</CardDescription>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="course-name">
              Course Name
            </Label>
            <Input defaultValue="Introduction to Biology" id="course-name" />
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="course-description">
              Description
            </Label>
            <Textarea
              className="min-h-[100px] max-h-[200px] h-[auto] resize-y"
              defaultValue="This course provides an overview of the basic principles of biology."
              id="course-description" />
          </div>
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="course-image">
              Image
            </Label>
            <Input accept="image/*" id="course-image" type="file" />
            <img
              alt="Course image"
              className="aspect-[2/1] overflow-hidden rounded-lg"
              height={100}
              src="/placeholder.svg"
              width={200} />
          </div>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label className="text-base" htmlFor="total-seats">
              Total Seats
            </Label>
            <Input defaultValue="100" id="total-seats" min="0" type="number" />
          </div>
          <div className="grid gap-2">
            <Label className="text-base">Quotas</Label>
            <div className="grid gap-2">
              <div className="grid gap-2 items-center md:grid-cols-2">
                <Label className="text-sm" htmlFor="quota-1-name">
                  Quota 1 Name
                </Label>
                <Input className="max-w-sm" id="quota-1-name" placeholder="Enter name" />
                <Label className="text-sm" htmlFor="quota-1-seats">
                  Seats
                </Label>
                <Input
                  className="max-w-xs"
                  id="quota-1-seats"
                  placeholder="Enter seats"
                  type="number" />
              </div>
            </div>
            <div className="grid gap-2 items-center md:grid-cols-2">
              <Label className="text-sm" htmlFor="quota-2-name">
                Quota 2 Name
              </Label>
              <Input className="max-w-sm" id="quota-2-name" placeholder="Enter name" />
              <Label className="text-sm" htmlFor="quota-2-seats">
                Seats
              </Label>
              <Input
                className="max-w-xs"
                id="quota-2-seats"
                placeholder="Enter seats"
                type="number" />
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter className="justify-end">
        <Button>Save</Button>
      </CardFooter>
    </Card>)
  );
}
