"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NRpJbYD07kj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogHeader, DialogFooter, DialogContent, Dialog } from "@/components/ui/dialog"

import { useState } from "react"
export function AllotmentAddModal({enrollments  , setIsOpen}) {
  
  return (
    (<Dialog defaultOpen>
      <DialogTrigger asChild>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>NRI Enrollments Success</DialogTitle>
        </DialogHeader>
        <div className="grid gap-4 py-4">            <div className="grid grid-cols-[1fr,auto] items-center gap-4">
              <div>
                <h4 className="font-medium">cs</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">5 allotted</p>
              </div>
              <CheckIcon className="h-5 w-5 text-green-500" />
            </div>
            <div className="grid grid-cols-[1fr,auto] items-center gap-4">
              <div>
                <h4 className="font-medium">ece</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">5 allotted</p>
              </div>
              <CheckIcon className="h-5 w-5 text-green-500" />
            </div>

        </div>
        <DialogFooter>
          <Button type="submit" onClick={(e)=>setIsOpen(false)}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>)
  );
}

function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}
