/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QAErVypmOBN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function courseList() {
  return (
  <div>
    <header className="bg-gray-900 py-4 text-white">
      <div
        className="container mx-auto flex items-center justify-between px-4 md:px-6">
        <div>
          <h1 className="text-2xl font-bold">Admission Portal</h1>
        </div>
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2">
            <UsersIcon className="h-5 w-5" />
            <span className="text-lg font-medium">2,345 Students</span>
          </div>
        </div>
      </div>
    </header>
    <main className="py-12 md:py-16 lg:py-20">
      <div className="container mx-auto px-4 md:px-6">
        <h2 className="mb-8 text-3xl font-bold">Courses</h2>
        <div
          className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Computer Science</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <span>Total Students</span>
                <span className="font-medium">450</span>
              </div>
              <div className="flex items-center justify-between">
                <span>General</span>
                <span className="font-medium">300</span>
              </div>
              <div className="flex items-center justify-between">
                <span>Reserved</span>
                <span className="font-medium">150</span>
              </div>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Electrical Engineering</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <span>Total Students</span>
                <span className="font-medium">320</span>
              </div>
              <div className="flex items-center justify-between">
                <span>General</span>
                <span className="font-medium">220</span>
              </div>
              <div className="flex items-center justify-between">
                <span>Reserved</span>
                <span className="font-medium">100</span>
              </div>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Mechanical Engineering</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <span>Total Students</span>
                <span className="font-medium">380</span>
              </div>
              <div className="flex items-center justify-between">
                <span>General</span>
                <span className="font-medium">260</span>
              </div>
              <div className="flex items-center justify-between">
                <span>Reserved</span>
                <span className="font-medium">120</span>
              </div>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Civil Engineering</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <span>Total Students</span>
                <span className="font-medium">400</span>
              </div>
              <div className="flex items-center justify-between">
                <span>General</span>
                <span className="font-medium">280</span>
              </div>
              <div className="flex items-center justify-between">
                <span>Reserved</span>
                <span className="font-medium">120</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  </div>);
}

function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
