/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3dprCJWhHtF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function CoursePrio() {
  return (
    (<div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center">
        <h2 className="text-2xl font-bold">Add Priority List</h2>
        <p className="text-gray-500 dark:text-gray-400">Select a course and set a priority level.</p>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="course">Course</Label>
            <Select id="course">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select course" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="math">Math</SelectItem>
                  <SelectItem value="english">English</SelectItem>
                  <SelectItem value="science">Science</SelectItem>
                  <SelectItem value="history">History</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="priority">Priority</Label>
            <Input
              id="priority"
              max="10"
              min="1"
              placeholder="Enter priority (1-10)"
              type="number" />
          </div>
        </div>
        <Button>Add</Button>
      </div>
      <div className="border rounded-lg p-4 space-y-2">
        <h3 className="text-lg font-medium">Priority List</h3>
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <div>Math</div>
            <div className="font-medium">1</div>
          </div>
          <div className="flex items-center justify-between">
            <div>English</div>
            <div className="font-medium">3</div>
          </div>
          <div className="flex items-center justify-between">
            <div>Science</div>
            <div className="font-medium">5</div>
          </div>
        </div>
      </div>
    </div>)
  );
}
