/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/z9HO7AjOdsw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function EnrolledList() {
  return (
    (<section className="w-full py-6 sm:py-12 md:py-24 lg:py-32 ">
      <div className="container px-4 md:px-6">
        <div className="flex items-center justify-normal mb-6">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">Student Details</h1>
        </div>
          <div className="flex items-center gap-2 justify-center">
            <Button variant="outline">All Students</Button>
            <Button variant="outline">Merit Quota</Button>
            <Button variant="outline">Management</Button>
          </div>
        <div
          className="overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-800 dark:border-gray-800">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Enrollment</TableHead>
                <TableHead>Program</TableHead>
                <TableHead>Semester</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>John Doe</TableCell>
                <TableCell>2021001</TableCell>
                <TableCell>Computer Science</TableCell>
                <TableCell>3</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Jane Smith</TableCell>
                <TableCell>2021002</TableCell>
                <TableCell>Electrical Engineering</TableCell>
                <TableCell>2</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Michael Johnson</TableCell>
                <TableCell>2021003</TableCell>
                <TableCell>Mechanical Engineering</TableCell>
                <TableCell>4</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Emily Davis</TableCell>
                <TableCell>2021004</TableCell>
                <TableCell>Civil Engineering</TableCell>
                <TableCell>1</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>David Lee</TableCell>
                <TableCell>2021005</TableCell>
                <TableCell>Computer Science</TableCell>
                <TableCell>5</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Sarah Kim</TableCell>
                <TableCell>2021006</TableCell>
                <TableCell>Electrical Engineering</TableCell>
                <TableCell>3</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Alex Patel</TableCell>
                <TableCell>2021007</TableCell>
                <TableCell>Mechanical Engineering</TableCell>
                <TableCell>2</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Olivia Nguyen</TableCell>
                <TableCell>2021008</TableCell>
                <TableCell>Civil Engineering</TableCell>
                <TableCell>4</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </section>)
  );
}
