"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5xo071193NB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardContent, Card, CardTitle, CardHeader } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { AllotmentAddModal } from "./allotment-add-modal"
import { useState } from "react"

export function Hero() {
  
  const [isOpen , setIsOpen] = useState(false);
  const [reducedData, setReducedData] = useState([]);

  return (

    (<main className="flex flex-col gap-8 p-6 md:p-8 lg:p-10">
      {
        isOpen && <AllotmentAddModal enrollments={reducedData} setIsOpen={setIsOpen} />
      }
      <header className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Actions</h1>
      </header>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <div className="col-span-2 md:col-span-1 lg:col-span-2">
          <div className="grid grid-cols-1 gap-4">
            <Card>
              <CardContent className="flex flex-col gap-4">
                <div>
                  <h3 className="text-lg font-medium">Allot Seats for NRI</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Approve seats for NRI based on their percentage and priority.
                  </p>
                </div>
                <Button variant="outline"
                  onClick={async () => {
                    console.log("Allot NRI");
                    const res = await fetch(`/api/actions/nri-allot`)

                    if (res.ok) {
                      const data = await res.json();
                      console.log("Allot NRI success" , data);
                      const reducedData = data.allotments.map(item => ({
                        courseId: item.courseId,
                        allotments: data.allotments.filter(i => i.courseId === item.courseId).length,
                      }));
                      setReducedData(reducedData);
                      setIsOpen(true);

                             
                    }

                  }
                }
                >Allot NRI</Button>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex flex-col gap-4">
                <div>
                  <h3 className="text-lg font-medium">Conduct Webinar</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Conduct a webinar on the latest trends in technology for NRI students.
                  </p>
                </div>
                <Button variant="outline">View Details</Button>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex flex-col gap-4">
                <div>
                  <h3 className="text-lg font-medium">Offer Internships</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Offer internships to NRI students to provide them with real-world experience.
                  </p>
                </div>
                <Button variant="outline">View Details</Button>
              </CardContent>
            </Card>
          </div>
        </div>
        <div className="col-span-1 md:col-span-1 lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Allot to NRI Students</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="action">Action</Label>
                <Select id="action">
                  <option>Select an action</option>
                  <option>Organize Hackathon</option>
                  <option>Conduct Webinar</option>
                  <option>Offer Internships</option>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="students">Number of NRI Students</Label>
                <Input id="students" type="number" />
              </div>
              <Button className="w-full">Allot</Button>
            </CardContent>
          </Card>
        </div>
      </div>
      <div>
        <Card>
          <CardHeader>
            <CardTitle>Logs</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Action</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>NRI Students Allotted</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>Organize Hackathon</TableCell>
                  <TableCell>2023-04-15</TableCell>
                  <TableCell>50</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Conduct Webinar</TableCell>
                  <TableCell>2023-05-01</TableCell>
                  <TableCell>30</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Offer Internships</TableCell>
                  <TableCell>2023-06-01</TableCell>
                  <TableCell>20</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </main>)
  );
}
