/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BpuLWdsGjdp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Manrope } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Notifications() {
  return (
    (<div className="grid gap-6 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>Course: Introduction to Computer Science</CardTitle>
          <CardDescription>Last added application</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1">
          <h3 className="text-sm font-bold">John Doe</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">Applied for the course.</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Course: Introduction to Computer Science</CardTitle>
          <CardDescription>Last left application</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1">
          <h3 className="text-sm font-bold">Alice Johnson</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">Left the application process.</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Course: Introduction to Computer Science</CardTitle>
          <CardDescription>Last transformed application</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1">
          <h3 className="text-sm font-bold">Emma Williams</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">Transformed the application into enrollment.</p>
        </CardContent>
      </Card>
    </div>)
  );
}
