"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KCd91mPo7gK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from 'react';


export function NRI() {
  const [form, setFormState] = useState({
    applicationNo: '',
    name: '',
    email: '',
    dateOfBirth: null,
    district: '',
    state: '',
    street: '',
    school: '',
    graduationYear: 2026,
    percentage: '',
    major: '',
    phone: '',
    address: ''
  });

  const handleInputChange = (event) => {
    setFormState({
      ...form,
      [event.target.id]: event.target.value
    });
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    try {
      const response = await fetch('/api/nri', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(form),
      });
  
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
  
      const data = await response.json();
      console.log(data);
  
      // Handle response data here
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const handleDateChange = (event) => {
    let value = event.target.value;    
    setFormState({
      ...form,
      [event.target.id]: value
    });
  };  



  return (
    (
    <form onSubmit={handleSubmit} className="px-4 md:px-6 lg:px-8 py-6 space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold">NRI Applicants</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Please enter the details of the Non-Resident Indian applicants.
        </p>
      </div>
      <div className="space-y-4">
  <div className="grid grid-cols-2 gap-4">
    <div className="space-y-2">
      <Label htmlFor="applicationNo">Applicant No</Label>
      <Input id="applicationNo" placeholder="Enter applicant number" value={form.applicationNo} onChange={handleInputChange}/>
    </div>
    <div className="space-y-2">
      <Label htmlFor="name">Name</Label>
      <Input id="name" placeholder="Enter name" required value={form.name} onChange={handleInputChange}/>
    </div>
    <div className="space-y-2">
      <Label htmlFor="email">Email</Label>
      <Input value={form.email} onChange={handleInputChange}  id="email" placeholder="Enter email" required type="email" />
    </div>
    <div className="space-y-2">
      <Label htmlFor="dateOfbirth">Date of Birth</Label>
      <Input value={form.dateOfBirth} onChange={handleDateChange} id="dateOfbirth" placeholder="Enter date of birth" required type="date" />
    </div>
    <div className="space-y-2">
      <Label htmlFor="district">District</Label>
      <Input value={form.district} onChange={handleInputChange} id="district" placeholder="Enter district" required />
    </div>
    <div className="space-y-2">
      <Label htmlFor="state">State</Label>
      <Input value={form.state} onChange={handleInputChange} id="state" placeholder="Enter state" required />
    </div>
    <div className="space-y-2">
      <Label htmlFor="street">Street</Label>
      <Input value={form.street} onChange={handleInputChange} id="street" placeholder="Enter street" required />
    </div>
  </div>
  <div className="space-y-4">
  <h2 className="text-2xl font-bold">Academic Details</h2>
  <div className="grid grid-cols-2 gap-4">
    <div className="space-y-2">
      <Label htmlFor="school">School</Label>
      <Input value={form.school} onChange={handleInputChange} id="school" placeholder="Enter school name" required />
    </div>
    <div className="space-y-2">
      <Label htmlFor="graduationYear">Graduation Year</Label>
      <Input value={form.graduationYear} onChange={handleInputChange} id="graduationYear" placeholder="Enter graduation year" required type="number" />
    </div>
    <div className="space-y-2">
      <Label htmlFor="percentage">Percentage</Label>
      <Input value={form.percentage} onChange={handleInputChange} id="percentage" placeholder="Enter percentage" required type="number" />
    </div>
    <div className="space-y-2">
      <Label htmlFor="major">Major</Label>
      <Input value={form.major} onChange={handleInputChange} id="major" placeholder="Enter major" required />
    </div>
  </div>
</div>
      
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="phone">Phone</Label>
            <Input value={form.phone} onChange={handleInputChange} id="phone" placeholder="Enter your phone number" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="address">Address</Label>
            <Input value={form.address} onChange={handleInputChange} id="address" placeholder="Enter your address" required />
          </div>
        </div>
        <Button>Submit</Button>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800" />
      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Applicants</h2>
        <div className="w-full overflow-auto">
          <table
            className="w-full text-left bg-white border border-gray-200 dark:border-gray-800 dark:border-gray-800">
      <thead>
        <tr>
          <th className="p-3 font-bold">Name</th>
          <th className="p-3 font-bold">Email</th>
          <th className="p-3 font-bold">Phone</th>
          
        </tr>
      </thead>
            <tbody>
              <tr className="hover:bg-gray-100 dark:hover:bg-gray-900">
                <td className="p-3">Rahul Sharma</td>
                <td className="p-3">rahul@example.com</td>
                <td className="p-3">+91 99999 88888</td>
              </tr>
              <tr className="hover:bg-gray-100 dark:hover:bg-gray-900">
                <td className="p-3">Asha Patel</td>
                <td className="p-3">asha@example.com</td>
                <td className="p-3">+91 77777 66666</td>
              </tr>
              <tr className="hover:bg-gray-100 dark:hover:bg-gray-900">
                <td className="p-3">Sandeep Kumar</td>
                <td className="p-3">sandeep@example.com</td>
                <td className="p-3">+91 55555 44444</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </form>)
  );
}
