/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KCd91mPo7gK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function NRI() {
  return (
    (<div className="px-4 md:px-6 lg:px-8 py-6 space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold">NRI Applicants</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Please enter the details of the Non-Resident Indian applicants.
        </p>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" required type="email" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="phone">Phone</Label>
            <Input id="phone" placeholder="Enter your phone number" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="address">Address</Label>
            <Input id="address" placeholder="Enter your address" required />
          </div>
        </div>
        <Button>Submit</Button>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800" />
      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Applicants</h2>
        <div className="w-full overflow-auto">
          <table
            className="w-full text-left bg-white border border-gray-200 dark:border-gray-800 dark:border-gray-800">
            <thead>
              <tr className="bg-gray-100 dark:bg-gray-900">
                <th className="p-3 font-semibold">Name</th>
                <th className="p-3 font-semibold">Email</th>
                <th className="p-3 font-semibold">Phone</th>
              </tr>
            </thead>
            <tbody>
              <tr className="hover:bg-gray-100 dark:hover:bg-gray-900">
                <td className="p-3">Rahul Sharma</td>
                <td className="p-3">rahul@example.com</td>
                <td className="p-3">+91 99999 88888</td>
              </tr>
              <tr className="hover:bg-gray-100 dark:hover:bg-gray-900">
                <td className="p-3">Asha Patel</td>
                <td className="p-3">asha@example.com</td>
                <td className="p-3">+91 77777 66666</td>
              </tr>
              <tr className="hover:bg-gray-100 dark:hover:bg-gray-900">
                <td className="p-3">Sandeep Kumar</td>
                <td className="p-3">sandeep@example.com</td>
                <td className="p-3">+91 55555 44444</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>)
  );
}
