/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3D9Wu85Pn59
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function SeatInfo() {
  return (
    (<div className="grid gap-6 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>Computer Science</CardTitle>
          <CardDescription>Seats: 60</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1.5">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Allotted</p>
            <p className="text-sm font-medium">30</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Quota</p>
            <p className="text-sm font-medium">10</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">NRI</p>
            <p className="text-sm font-medium">5</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Remaining</p>
            <p className="text-sm font-medium">15</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Electrical Engineering</CardTitle>
          <CardDescription>Seats: 60</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1.5">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Allotted</p>
            <p className="text-sm font-medium">20</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Quota</p>
            <p className="text-sm font-medium">15</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">NRI</p>
            <p className="text-sm font-medium">10</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Remaining</p>
            <p className="text-sm font-medium">25</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Mechanical Engineering</CardTitle>
          <CardDescription>Seats: 60</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1.5">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Allotted</p>
            <p className="text-sm font-medium">25</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Quota</p>
            <p className="text-sm font-medium">5</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">NRI</p>
            <p className="text-sm font-medium">10</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Remaining</p>
            <p className="text-sm font-medium">25</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Civil Engineering</CardTitle>
          <CardDescription>Seats: 60</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-1.5">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Allotted</p>
            <p className="text-sm font-medium">30</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Quota</p>
            <p className="text-sm font-medium">5</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">NRI</p>
            <p className="text-sm font-medium">10</p>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium">Remaining</p>
            <p className="text-sm font-medium">20</p>
          </div>
        </CardContent>
      </Card>
    </div>)
  );
}
